version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
   configuration: docs/source/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/source/requirements.readthedocs.txt
