name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.11
      with:
        python_version: "3.11"
        pypi_token: ${{ secrets.PYPI_TOKEN }}
